= ft-fms-multipass
:experimental:
:hide-uri-scheme:

* <<About>>
* <<Installation on macOS>>
* <<Installation on Windows 10>>
* <<Administration>>
* <<Issues>>

== About

Run FileMaker Server 19.3 for Ubuntu in Multipass for Mac or Windows. Everything you need to automatically build a ready-to-run Instance.

We are constantly improving the scripts and try to get rid of the remaining issues. If you want to stay up-to-date, make sure to watch the repo and maybe follow us on Twitter: https://twitter.com/fmgarage[@fmgarage]

TIP: Also see https://github.com/fmgarage/ft-fms-docker[ft-fms-docker], our approach to run FileMaker Server in Docker. While Multipass is even more lightweight, and a little easier to use due to its focused nature, it is not yet as mature as Docker and still yields some bugs and missing features. +
The mount of external volumes for example doesn't handle ownership mapping the way it should, so FileMaker Server directories must be accessed via SFTP instead. +
On the other hand, with multipass, it is possible to run multiple FileMaker Servers in parallel.

.What does 'FT' stand for?
All our **FileMaker**-based projects and products are prefixed with an **F**, and the **T** is for **tools, technology, tipps&tricks, techniques** or open **templates** for the community. These files are basically examples and demonstrations where you can copy stuff from and include it your individual apps and solutions.

Browse all our FT repos:

https://github.com/fmgarage?q=ft-

If you are looking for other ways to run a FileMaker Server for Linux, check out our regarding repos:

https://github.com/fmgarage?q=ft-fms-

== Installation on macOS

=== Multipass

Download and install Multipass and make sure it is running: https://multipass.run

=== Repo

Clone or download the repo.

=== FileMaker Server

Download a copy of the FileMaker Server installer for Linux from your Claris account page, unpack the zip file and move the `deb` file to the folder where you put the repo. You can also put a link into the config.txt instead, the installer will be downloaded then.

=== SSH key pair generation

If you want to connect to the instance's filesystem without a password, and you don't already have a public/private ssh key pair, you will need to create one. With the following command, a key pair gets generated and saved to your home directory in the `.ssh` folder:

    ssh-keygen -t rsa -b 4096

=== Config

Adjust settings in `config.txt`

- Set instance name. Must be unique.

    instance_name=fms1

- Set resources for the instance. Leave empty for default values.

include::doc/admo_disk.adoc[]

    cpus=1
    add_disk=2
    mem=2

- Set path to ssh public key for key-based SFTP file access. Leave empty for password authentication.

    ssh_pub_key_path=/Users/nancy/.ssh/id_rsa.pub

You can adjust the settings for the _Assisted Install.txt_ file in the `config.txt`, but you don't need to. The server admin console login will be admin/admin then, which can be changed later.

//include::doc/build.adoc[]

=== Build and run Instance

Open Terminal.app, drag the `launch.sh` into the terminal window and hit return.

After the installation process finishes, the IP of the instance will be printed out by the script.
Also check the multipass menu, there should be a running instance named like set in `config.txt`.

Open the admin console by browsing to with `\https://<IP_from_output>:16000`

Mind that:

* *Chrome* does not work without a valid certificate
* *Safari* lets you bypass the certificate warning
* *Edge* lets you bypass the certificate warning, but you need to append `https://`.

Clicking `Open Shell` from the Multipass menu will open a terminal window where you can use the fmsadmin command to control your server.

== Installation on Windows 10

=== WSL2

Install the Windows Subsystem for Linux *WSL* first. To do so, follow these instructions: https://docs.microsoft.com/de-de/windows/wsl/install-win10 ("Manual Installation Steps").

=== Ubuntu

Download and install Ubuntu from the Windows Store. The `Ubuntu` and `Ubuntu 20.04` apps are identical, just make sure it is the one offered by Canonical Group Limited.
When installed, update packages:

[source,shell]
----
sudo apt update
sudo apt upgrade
----

Most likely, it will be necessary to restart Ubuntu after the update, which in this case is done by leaving the linux environment with

[source,shell]
----
exit
----

and then starting Ubuntu again.

=== Multipass

Download and install Multipass and make sure it is running: https://multipass.run

=== Repo

Clone or download and unzip the repo.

=== FileMaker Server

Download a copy of the FileMaker Server installer for Linux from your Claris account page, unpack the zip file and move the `deb` file to the folder where you put the repo. You can also put a link into the config.txt instead, the installer will be downloaded then.

=== SSH key pair generation

If you want to connect to the instance's filesystem without a password, and you don't already have a public/private ssh key pair, you will need to create one. With the following command, a key pair gets generated and saved to your home directory in the `.ssh` folder:

    ssh-keygen -t rsa -b 4096

Then, from WinSCP or PuTTY or the Windows SFTP client of your choice, you might need to convert the private key to the PuTTY ppk format.

=== Config

Adjust settings in `config.txt`

- Set instance name. Must be unique.

    instance_name=fms1

- Set resources for the instance. Leave empty for default values.

include::doc/admo_disk.adoc[]

    cpus=1
    add_disk=2
    mem=2

- Set path to ssh public key for key-based SFTP file access. Leave empty for password authentication.

    ssh_pub_key_path=/mnt/c/Users/nancy/.ssh/id_rsa.pub

You can adjust the settings for the _Assisted Install.txt_ file in the `config.txt`, but you don't need to. The server admin console login will be admin/admin then, which can be changed later.

=== Run install script

In Ubuntu shell, run the installer from the folder where you put the repository:

----
/mnt/c/Users/<User>/Downloads/ft-fms-multipass/launch.sh
----

After the installation process finishes, the IP of the instance will be printed out by the script.
Or/Also check the multipass menu in the Taskbar, there should be a running instance named like set in `config.txt`.

Open the admin console by browsing to with `\https://<IP_from_output>:16000`

Mind that:

* *Chrome* does not work without a valid certificate
* *Edge* lets you bypass the certificate warning, but you need to append `https://`.

Clicking `Open Shell` from the Multipass menu will open a terminal window where you can use the fmsadmin command to control your server.

== Administration

=== Stopping and Restarting the Server

At the moment, quitting Multipass will not gracefully close your databases or stop the server. To prevent your databases from being corrupted from a hard shutdown, always stop the server with the `fmsadmin stop server` command beforehand.

=== Accessing files

Since mounts in multipass are not versatile/mature enough to present parts of the inside filesystem to the user, the best approach is to connect via sftp.

Recommendable clients for Windows are *WinSCP* or *PuTTY*.

The user is `fmserver`, since it has the needed permissions. Set the ssh key as authentication method.

The FileMaker Server directory inside the multipass instance is `/opt/FileMaker/FileMaker Server/`. Mind the whitespaces in the path.

=== Managing Instances

Some multipass commands that might be useful:

show instances, including IP address:

    multipass ls

stop instance:

    multipass stop <instance-name>

delete instance:

    multipass delete <instance-name>

really remove deleted instances:

    multipass purge

Find more at the official Multipass Docs:

https://multipass.run/docs

== Issues

We have experienced situations where multipass could not start up anymore. These situations where probably caused by stopping, deleting and purging instances to fast successively. This is also the reason why the reboot option has been taken out of the cloud-config. The following issue might be related and also contains a workaround to handle this:

https://github.com/canonical/multipass/issues/1983

Resources for any created instance cannot be altered afterwards.

https://github.com/canonical/multipass/issues/62

In Windows, IP addresses of instances change randomly after Windows reboot. Find the current IP with

    multipass ls

https://github.com/canonical/multipass/issues/1293
